language: bash

os: linux

services: docker

dist: bionic

jobs:
  include:
     
   - stage: building x86_64 image
     arch: amd64
     script: chmod +x ./build.sh; ./build.sh
     
   - stage: building s390x image
     arch: s390x
     script: chmod +x ./build.sh; ./build.sh
     
   - stage: building ppc64le image
     arch: ppc64le
     script: chmod +x ./build.sh; ./build.sh
     
   - stage: building multi-arch image
     arch: amd64
     script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
