language: bash

os: linux

services: docker

dist: bionic

jobs:
  include:
   - stage: building ppc64le image
     arch: ppc64le
     script: chmod +x ./build.sh; ./build.sh
   #- stage: building x86_64 image
   #  arch: amd64
   #  script: chmod +x ./build.sh; ./build.sh
  # - stage: building multi-arch image
   #  arch: ppc64le
   #  script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
   #- stage: run x86_64 image
   #  arch: amd64
   #  script: docker pull quay.io/rpsene/multi-arch-travis:latest; docker run --rm quay.io/rpsene/multi-arch-travis:latest
   #- stage: run ppc64le image
   #  arch: ppc64le
   #  script: docker pull quay.io/rpsene/multi-arch-travis:latest; docker run --rm quay.io/rpsene/multi-arch-travis:latest
