language: bash

os: linux

services: docker

dist: bionic

jobs:
  include:
   - name: building x86_64 image 
     arch: amd64
     script: chmod +x ./build.sh; ./build.sh
   - name: building ppc64le image
     arch: ppc64le 
     script: chmod +x ./build.sh; ./build.sh
   - stage: building multi-arch using ppc64le as host
     arch: ppc64le
     script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
