language: bash

os: linux

services: docker

dist: bionic

name: multi-arch build

jobs:
  include:
   - arch: amd64
   - arch: ppc64le
   script: chmod +x ./build.sh; ./build.sh
   stage: building multi-arch using ppc64le as host
    arch: ppc64le
    script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
