language: bash

jobs:
  include:
   - os: linux
     arch: amd64
     script: docker built -t container/amd64 -f /x86_64/Dockerfile .
   - os: linux
     arch: ppc64le
     script: docker built -t container/ppc64le -f /ppc64le/Dockerfile .
   - os: linux
     arch: s390x
     script: docker built -t container/s390x -f /s390x/Dockerfile .
