language: bash

services: docker

dist: bionic

jobs:
  include:
   - os: linux
     arch: amd64
     script: chmod +x ./build.sh; ./build.sh
   - os: linux
     arch: ppc64le
     script: chmod +x ./build.sh; ./build.sh
