language: bash

os: linux

services: docker

dist: bionic

name: multi-arch build

jobs:
  include:
    - arch: amd64
      script: chmod +x ./build.sh; ./build.sh
    - arch: ppc64le
      script: chmod +x ./build.sh; ./build.sh
