language: bash

os: linux

services: docker

dist: bionic

name: multi-arch image build

jobs:
  include:
    - arch: amd64
      script: chmod +x ./build.sh; ./build.sh
    - arch: ppc64le
      script: chmod +x ./build.sh; ./build.sh
    - stage: deploy
      arch: ppc64le
      script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
