language: bash

os: linux

services: docker

dist: bionic

jobs:
  include:
    - arch: amd64
      name: Intel
      script: chmod +x ./build.sh; ./build.sh
    - arch: ppc64le
      name: Power      
      script: chmod +x ./build.sh; ./build.sh
    - stage:
      name: Creating multi-arch images
      arch: ppc64le
      script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
